version: '2'
services:
  db:
    image: postgres
    container_name: ccbadm-db
    user: "root"
    volumes:
      - /mnt/disk2/ccbadm:/var/lib/postgresql/data/pgdata
      # - /data/ccbadm-db:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGUSER=postgres
      - POSTGRES_DB=ccbadm
      - POSTGRES_PASSWORD=ot_VVsYskexKUWUb88gZdMWbd9
    ports:
      - '5432:5432'
    restart: always
  cache:
    image: memcached
    container_name: ccbadm-cache
    restart: always
  api:
    image: jesse1983/ccbadm-api:latest
    command: bundle exec puma -C config/puma.rb
    # command: rails s -e "production"
    container_name: ccbadm-api
    environment:
      RACK_ENV: production
      RAILS_ENV: production
      DATABASE_NAME: ccbadm
      DATABASE_HOST: ccbadm-db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ot_VVsYskexKUWUb88gZdMWbd9
      MEMCACHED_URL: ccbadm-cache:11211
      SECRET_KEY_BASE: 329c8c15894bec1a9816ce4bcd5a0b5f198f8bcfb2451fdcc928d69654631fb3c54170e8f68f2a5574b1881309fef729e1458ac09738e4659e29fed85f5fbc50
      SOME_API_KEY: CCBADMApiKey
    ports:
      - '3000:3000'
    depends_on:
      - db
      - cache
    stdin_open: true
    tty: true
    restart: always
  web:
    image: jesse1983/ccbadm-web:latest
    command: npm start
    container_name: ccbadm-web
    environment:
      PORT: 80
      ENV: production
      NODE_ENV: production
    ports:
      - '80:80'
    depends_on:
      - api
    restart: always
