development:
  adapter: postgresql
  encoding: UTF8
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

production:
  adapter: postgresql
  encoding: UTF8
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>